#!/bin/bash

# Manual VPS Commands - Copy and paste these in your SSH session

echo "Execute these commands on your VPS after connecting:"
echo "=================================================="
echo ""
echo "# 1. Create backup directory"
echo "BACKUP_DIR=/tmp/whisky-backup-\$(date +%Y%m%d-%H%M%S)"
echo "mkdir -p \$BACKUP_DIR"
echo "echo \"Backup directory: \$BACKUP_DIR\""
echo ""
echo "# 2. Backup existing files"
echo "if [ -d '/var/www/viticultwhisky' ]; then"
echo "    find /var/www/viticultwhisky -name '*.env*' -not -path '*/node_modules/*' -exec cp {} \$BACKUP_DIR/ \\; 2>/dev/null || true"
echo "    [ -d '/var/www/viticultwhisky/uploads' ] && cp -r /var/www/viticultwhisky/uploads \$BACKUP_DIR/"
echo "    echo \"Files backed up\""
echo "fi"
echo ""
echo "# 3. Backup database"
echo "systemctl start mongod"
echo "sleep 5"
echo "mongodump --db=viticult_whisky --out=\$BACKUP_DIR/mongodb/ 2>/dev/null || echo 'No database to backup'"
echo "systemctl stop mongod"
echo ""
echo "# 4. Remove old project"
echo "rm -rf /var/www/viticultwhisky"
echo "echo \"Old project deleted\""
echo ""
echo "# 5. Clone fresh from GitHub"
echo "cd /var/www"
echo "git clone https://github.com/adityapachauri0/whisky.git viticultwhisky"
echo "cd viticultwhisky"
echo ""
echo "# 6. Create backend .env"
echo "cat > backend/.env << 'EOF'"
echo "NODE_ENV=production"
echo "PORT=5000"
echo "MONGODB_URI=mongodb://localhost:27017/viticult_whisky"
echo "JWT_SECRET=whisky-jwt-secret-production-2024"
echo "EMAIL_HOST=smtp.gmail.com"
echo "EMAIL_PORT=587"
echo "EMAIL_USER=your-email@gmail.com"
echo "EMAIL_PASS=your-app-password"
echo "CORS_ORIGIN=https://viticultwhisky.co.uk"
echo "EOF"
echo ""
echo "# 7. Create frontend .env"
echo "cat > frontend/.env << 'EOF'"
echo "REACT_APP_API_URL=https://viticultwhisky.co.uk/api"
echo "REACT_APP_ENVIRONMENT=production"
echo "EOF"
echo ""
echo "# 8. Install backend dependencies"
echo "cd backend"
echo "npm ci --production"
echo "cd .."
echo ""
echo "# 9. Install frontend and build"
echo "cd frontend"
echo "npm ci"
echo "npm run build"
echo "cd .."
echo ""
echo "# 10. Set permissions"
echo "chown -R www-data:www-data /var/www/viticultwhisky"
echo ""
echo "# 11. Start services"
echo "systemctl start mongod"
echo "systemctl enable mongod"
echo ""
echo "pm2 delete all 2>/dev/null || true"
echo "pm2 start backend/server.js --name 'whisky-backend'"
echo "pm2 startup"
echo "pm2 save"
echo ""
echo "systemctl start nginx"
echo "systemctl enable nginx"
echo ""
echo "# 12. Check status"
echo "pm2 status"
echo "systemctl status nginx --no-pager -l"
echo "echo 'Deployment complete!'"