#!/bin/bash

echo "🔐 Secure Secret Generator"
echo "========================="
echo ""
echo "Generate these secure values for production .env:"
echo ""
echo "# Security Secrets (Generated on $(date))"
echo "JWT_SECRET=$(openssl rand -hex 32)"
echo "SESSION_SECRET=$(openssl rand -hex 32)" 
echo "CSRF_SECRET=$(openssl rand -hex 32)"
echo "COOKIE_SECRET=$(openssl rand -hex 32)"
echo "ENCRYPTION_KEY=$(openssl rand -hex 16)"
echo ""
echo "⚠️  IMPORTANT:"
echo "1. Copy these values to your production .env file"
echo "2. Never commit these values to git"
echo "3. Store them securely (password manager, secrets vault)"
echo "4. Your admin password remains 'admin123' - these are different secrets"