#!/bin/bash

echo "🚀 Deploying Email Template Update to VPS"
echo "========================================"

echo "1. SSH into your VPS:"
echo "   ssh root@31.97.57.193"
echo ""
echo "2. Once logged in, run these commands:"
echo ""
echo "cd /var/www/viticultwhisky"
echo "git pull origin main"
echo ""
echo "# Restart the backend with the new changes"
echo "sudo -u nodeapp pm2 restart viticult-backend"
echo ""
echo "# Check if everything is running"
echo "sudo -u nodeapp pm2 status"
echo ""
echo "3. Test the email preview:"
echo "   - Go to https://viticultwhisky.co.uk/admin"
echo "   - Login with your admin credentials"
echo "   - Click 'View' on any contact"
echo "   - Click 'Send Email' to see the beautiful template"
echo ""
echo "Note: Email sending will fail without SMTP credentials,"
echo "but you should see the beautiful email preview!"